version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react-monaco-editor"  # version is set by patternfly/react-code-editor
