version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allowed-updates:
      - match:
          update_type: "security"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    allowed-updates:
      - match:
          update_type: "security"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Submodule update"
