---
name: Build binary

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install Node with caching
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ui
          useRollingCache: true

      - name: Build adash
        run: make adash

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Altinity Dashboard
          path: adash

