---
name: Lint and Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Build the embed files
        run: make embed

      - name: Build the UI
        run: make ui

      - name: Run Go linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          skip-go-installation: true

      - name: Run Javascript linter
        run: cd ui && npx eslint --max-warnings=0 src/

      - name: Check node modules security
        run: cd ui && npm audit --audit-level moderate

      - name: Build adash
        run: make adash

      - name: Build platform binaries (to make sure it works)
        run: make bin

      - name: Build container image (to make sure it works)
        run: docker build .

